### ISSUE TITLE
Bot will not play sound on Windows

### ISSUE THREAD

**Issue by SloppierKitty7** [martinmine/discord-music-bot#2]
using !play and then and i'd just returns with "grabbing track info for 7xvpcXvNwJs" and no sound will play

**Comment by martinmine** [comment]
What OS are you using for the bot? In case of Windows, I have not been able to successfully make the bot play any audio. I'm currently running this bot from an Ubuntu server.

**Comment by SloppierKitty7** [comment]
was running it windows but will try it a arch or debian server what are you using to actually get the audio because i think that may be the problem?

**Comment by martinmine** [comment]
The bot will download the audio from youtube using [youtube-dl](https://www.npmjs.com/package/youtube-dl) for node.js, the discord.js framework will then play the file directly from the file-system. In case this info becomes useful, I run the bot on an Ubuntu 14.04 server, follow these steps to set up the discord.js required stuff for the bot: https://discordjs.readthedocs.io/en/latest/installing.html 
But imo, it is strange that it is stuck on "grabbing track info..." as that would indicate that the youtube-dl itself can't download the file. However, if that was the case, it _should_ show an error message. When I tried requesting the video-id you provided, it was able to fetch it: https://i.shikashi.me/59ke7 
It might be that you have to wait a bit as it downloads the file. I'm aware that downloading the file isn't the perfect solution, but better than relying on shitty/shady 3rd-party Youtube MP3 converters that downloads the file at their end anyways. As you can see on the original project ([which also has an issue related to sound playback on Windows](https://github.com/agubelu/discord-music-bot/issues/6)), it uses a service called savedeo.com to get the audio link. I experienced far more lag and issues with broken audio when using this service as the bot would stream the audio while playing it.

**Comment by SloppierKitty7** [comment]
so i installed it on ubuntu 16.04 and got the following 


[15:00:20] SloppierKitty7 -> request https://www.youtube.com/watch?v=PfD9SlF8QRU
[15:00:23] NP: "Pat Lok - You Street" (by SloppierKitty7)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn help ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
neil@ubuntu:~/bot_$

**Comment by martinmine** [comment]
Did you run

> sudo add-apt-repository ppa:mc3man/trusty-media && sudo apt-get update && sudo apt-get install ffmpeg

as mentioned by the docs for setting discord.js up on Ubuntu?

**Comment by SloppierKitty7** [comment]
i've did that now but its just hanging after the "grabbing track info for PfD9SlF8QRU" i still still add songs but i will never play i installed the other version of the bot and it would get the song and stat playing it but there was no sound

**Comment by martinmine** [comment]
Try run

> $ sudo apt-get install build-essential
> $ npm install --save discord.js

Also, run npm install after executing the previous commands.

**Comment by SloppierKitty7** [comment]
https://i.gyazo.com/2c9ee1f785e887b8f55f50c03364adea.png

i don't even know anymore

**Comment by martinmine** [comment]
As I see it, this could be a networking problem, for example your firewall doesn't allow outgoing connections (which it does, otherwise the other version wouldn't work either), or Youtube may be blocking your data center's IP range which I think is the most likely scenario (or the other way around). Normally, the bot should show "grabbing track info for PfD9SlF8QRU", then replace the message with a "added to queue" message. 

Also, I see you're running on Ubuntu 16.04, which could have some compatibility issues or something with discord.js.

**Comment by SloppierKitty7** [comment]
ya i think running it in a vm is what's wrong. were you running it in a vm or was it an actual server

**Comment by martinmine** [comment]
I'm currently running it on the smallest instance that DigitalOcean offers (5$/month vps). Whether its on a vm or not shouldn't really matter, I'm more concerned that you're on 16.04. If you go with DigitalOcean, you can easily select 14.04 when setting up the vps. Also hosted it at Vultr earlier without any issues (Also Ubuntu 14.04).

**Comment by martinmine** [comment]
This should be solved with the last commit (Can play music on W10).
